# Block D from the keyword document, English column. Every answer is lifted
# word for word from an existing English page; nothing here was written for
# this page.
GROEPEN = [
 ("Storage and storage paths", "storage", [
  ("Check MPIO settings",
   "MPIO with Round Robin on an active/passive array that strongly prefers one controller.",
   "/en/blog/top-10-hyper-v-cluster-issues/", "Ten issues we keep finding"),
  ("Check Fibre Channel zoning",
   "Zoning, fabric layout, port status and path redundancy where storage runs over Fibre Channel.",
   "/en/modules/", "The modules"),
  ("Storage path redundancy",
   "The array itself: firmware, pools, LUNs, host mappings and path layout, against what the hosts see on their side.",
   "/en/modules/", "The modules"),
  ("Outdated storage NIC driver",
   "Firmware drift is invisible to most monitoring tools because the values sit in the BMC or NIC EEPROM, not in Windows.",
   "/en/blog/top-10-hyper-v-cluster-issues/", "Ten issues we keep finding"),
 ]),
 ("Firmware and management cards", "firmware", [
  ("Cluster firmware baseline",
   "Set a baseline (vendor solution profile from Dell, HPE or Lenovo), document it in your runbook, and upgrade the cluster as a whole during a planned window.",
   "/en/blog/top-10-hyper-v-cluster-issues/", "Ten issues we keep finding"),
  ("iDRAC firmware versions out of step",
   "Hardware, firmware and BIOS settings over iDRAC, iLO or XClarity; also usable on a node that is not running at the time.",
   "/en/modules/", "The modules"),
  ("Read hardware over Redfish",
   "Hardware, firmware and BIOS settings over iDRAC, iLO or XClarity; also usable on a node that is not running at the time.",
   "/en/modules/", "The modules"),
 ]),
 ("Network and performance", "network", [
  ("Cluster network separation",
   "The cluster only considers networks with role Cluster or ClusterAndClient for internal traffic, including Live Migration.",
   "/en/blog/live-migration-wrong-network/", "Live Migration on the wrong network"),
  ("ntttcp network throughput test",
   "A repeatable load measurement with fio and ntttcp, only inside an agreed maintenance window.",
   "/en/modules/", "The modules"),
  ("fio benchmark cluster storage",
   "A repeatable load measurement with fio and ntttcp, only inside an agreed maintenance window.",
   "/en/modules/", "The modules"),
 ]),
 ("Patching, time and updates", "patching", [
  ("Set up cluster aware updating",
   "Cluster Aware Updating has two operational modes, and the choice between them is a strategic decision affecting runbook, audit trail, and supportability.",
   "/en/blog/cluster-aware-updating-runbook-audit-trail/", "Cluster Aware Updating: runbook and audit trail"),
  ("Patching without losing redundancy",
   "Because during a patch round there is always a node out of rotation. With two nodes that means: one node carries everything and there is no second one to fall back on if something goes wrong in that window.",
   "/en/faq/", "Frequently asked questions"),
  ("Cluster time sync drift",
   "Acceptable skew between cluster nodes: under 1 second in steady state, under 5 seconds during a patch round or node reboot. Above 30 seconds is an urgent remediation topic.",
   "/en/blog/hyper-v-time-drift-kerberos-csv/", "Time drift in Hyper-V clusters"),
 ]),
 ("Security, identity and backup", "security", [
  ("Secure Boot disabled on host",
   "What it loses is the early-boot security pipeline: updates to the Windows Boot Manager, Secure Boot DB updates, DBX revocation-list updates, and mitigations for future boot-level vulnerabilities of the BlackLotus class (CVE-2023-24932).",
   "/en/blog/secure-boot-2023-certificates-hyper-v-gen2-vms/", "Secure Boot certificates and Hyper-V Gen 2 VMs"),
  ("Migrate generation 1 VMs",
   "Existing VMs are not updated when you patch the host, because their certificate state lives in their own NVRAM.",
   "/en/blog/secure-boot-2023-certificates-hyper-v-gen2-vms/", "Secure Boot certificates and Hyper-V Gen 2 VMs"),
  ("AD Tier 0 exposure",
   "Exposure of Tier 0 (Domain Controllers and other critical identity workloads) from this cluster. Off by default; runs only at your request.",
   "/en/modules/", "The modules"),
  ("Domain controller on the same cluster",
   "Exposure of Tier 0 (Domain Controllers and other critical identity workloads) from this cluster. Off by default; runs only at your request.",
   "/en/modules/", "The modules"),
  ("DRTM secured core server",
   "Azure Local, HCI and Storage Spaces Direct: pool and virtual disk health, Network ATC intents, Arc connectivity, secured-core posture, failover headroom.",
   "/en/partners/", "For partners"),
  ("No backup of cluster volumes",
   "The assessment of backup and management, beyond the presence check in the base measurement.",
   "/en/modules/", "The modules"),
 ]),
 ("Azure", "azure", [
  ("Azure Arc cluster registration",
   "Azure Arc remained mandatory, so there is no independent, non-Azure HCI to buy anymore.",
   "/en/blog/azure-local-vs-classic-hyper-v-cluster/", "Classic Hyper-V or Azure Local?"),
  ("Azure Migrate readiness per VM",
   "Per-VM migration readiness against what actually runs. Only together with M5.",
   "/en/modules/", "The modules"),
 ]),
]
